image: git01.iis.fhg.de:5005/mkj/vscode-extension-of-the-week

confluence:
  script:
    - pip install -e .
    - ./publish
  rules:
    # only publish from default branch
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_SERVER_HOST == "git01.iis.fhg.de"

html:
  script:
    - cp -r "VSCode Extension of the Week" public
    - pip install -e .
    - python md2html public
  artifacts:
    paths:
      - public

pages:
  needs:
    - html
  script:
    - cp -r img public/img
    - cd public
    - ls **/*.html
  artifacts:
    paths:
      - public
  rules:
    # only publish from default branch
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: never
