image: git01.iis.fhg.de:5005/mkj/vscode-extension-of-the-week

confluence:
  script:
    - pip install -e .
    - ./dev/publish
  rules:
    # only publish from default branch
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_SERVER_HOST == "git01.iis.fhg.de"

html:
  script:
    - cp -r "VSCode Extension of the Week" public
    - pip install -e .
    - python -m eotw update-toc README.md public --target public/index.md --url-ref "{year}/{week}"
    - python -m eotw build public
    - cp -r img public/img
  artifacts:
    paths:
      - public

pages:
  needs:
    - html
  script:
    - cd public
    - ls -R .
  artifacts:
    paths:
      - public
  only:
    - main
