image: git01.iis.fhg.de:5005/mkj/vscode-extension-of-the-week

confluence:
  script:
    - pip install -e .
    - ./publish
  rules:
    - if: $CI_SERVER_HOST == "git01.iis.fhg.de"

html:
  script:
    - cp -r "VSCode Extension of the Week" public
    - pip install -e .
    - python md2html2 public
  artifacts:
    paths:
      - public

pages:
  needs:
    - html
  script:
    - cp -r img public/img
    - cd public
    - ls **/*.html
  artifacts:
    paths:
      - public
